name: Deletion of aws environment
on:
  issue_comment:
    types: [created]

jobs:
  trigger-pr-branch-deletion:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      pull-requests: write
    if: >
      github.event.issue.pull_request &&
      github.event.issue.state == 'open' &&
      github.event.comment.body == '/destroy'
    steps:
      - name: Get Pull Request Head Ref
        id: get-head-ref
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const response = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            console.log(response.data);
            return response.data.head.ref;

  call-delete-workflow:
    # 👆 this is a NEW JOB, same indent as trigger-pr-branch-deletion
    needs: trigger-pr-branch-deletion
    if: needs.trigger-pr-branch-deletion.result == 'success'
    uses: ./.github/workflows/destroy.yml
    with:
      aws-env: github-actions-course-demo-pr-23   # hard-coded for testing
      github-env: staging
      report-pr: ${{ github.event.issue.number }}
    secrets: inherit
