name: cd.yml
on:
  push:
    branches:
      - main

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
jobs:
  create-version-pr-or-realise:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false   # <<< important
          fetch-depth: 0
      - name: Setup Node Environment
        uses: actions/setup-node@v6
        with:
          node-version: 18
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: create version PR or github realise
        id: changeset
        uses: changesets/action@v1
        with:
          publish: npx changesets tag
        env:
          GITHUB_TOKEN: ${{secrets.changesets_key}}
      - run: echo "${{toJSON(steps.changeset.outputs)}}"

      - name: Send a Slack Message for Version PR Updates
        if: steps.changeset.outputs.pullRequestNumber
        uses: slackapi/slack-github-action@v1
        continue-on-error: true
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "✅ *<https://github.com/${{github.repository}}/pull/${{ steps.changeset.outputs.pullRequestNumber }}|Version Pull Request>* was updated. Review it and merge it to create a new release and deployment."
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK




